# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SÅ‚awomir Konrad Tadeja
user_description: PhD Student in VR-tech with emphasis on visual analytics
user_title: PhD Student
email: slawomir.tadeja@alumni.cern
#twitter_username: lorem_ipsum
github_username:  skt40
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
